from sqlalchemy.orm import Session
from backend.models.models import MasterExercise

MASTER_EXERCISES_DATA = [
    {
        "name": "Barbell Bench Press",
        "category": "chest",
        "primary_muscle": "Middle Chest",
        "secondary_muscles": ["Triceps", "Front Delts"],
        "movement_pattern": "push",
        "equipment": "barbell",
        "difficulty": "intermediate",
        "skill_level": "intermediate",
        "instructions": ["Lie flat on bench", "Grasp bar slightly wider than shoulder width", "Lower bar smoothly to lower sternum", "Press up explosively while keeping feet planted"],
        "common_mistakes": ["Bouncing bar off chest", "Flaring elbows to 90 degrees", "Lifting hips off the bench"],
        "safety_tips": ["Use a spotter or power rack safety bars", "Keep wrist joint neutral", "Retract scapula before lifting"],
        "alternatives": ["Dumbbell Bench Press", "Machine Chest Press", "Weighted Push-Ups"],
        "progressions": ["Pause Bench Press", "Pin Press"],
        "regressions": ["Dumbbell Press", "Push-Ups"],
        "warmup_suggestions": ["Band Pull-Aparts 2x15", "Light Barbell Warmup 1x10"],
        "estimated_calories_per_min": 7.5,
        "typical_rpe": 8.0,
        "typical_rest_sec": 120,
        "tempo": "3-1-1-0",
        "tut_sec": 35,
        "rom_notes": "Touch chest without arching excessively",
        "grip_variations": ["Medium Grip", "Wide Grip", "Close Grip"]
    },
    {
        "name": "Incline Dumbbell Press",
        "category": "chest",
        "primary_muscle": "Upper Chest",
        "secondary_muscles": ["Front Delts", "Triceps"],
        "movement_pattern": "push",
        "equipment": "dumbbell",
        "difficulty": "intermediate",
        "skill_level": "intermediate",
        "instructions": ["Set bench to 30-45 degree incline", "Press dumbbells up and inward in a slight arc", "Lower with control until chest stretch"],
        "common_mistakes": ["Setting incline too high (>45 degrees)", "Dropping dumbbells abruptly"],
        "safety_tips": ["Tuck elbows 45 degrees to protect rotator cuff"],
        "alternatives": ["Incline Barbell Press", "Low-to-High Cable Flyes"],
        "progressions": ["Incline DB Press with Pause"],
        "regressions": ["Low Incline DB Press"],
        "warmup_suggestions": ["Arm Circles", "Light DB Press Warmup"],
        "estimated_calories_per_min": 6.8,
        "typical_rpe": 8.0,
        "typical_rest_sec": 90,
        "tempo": "2-1-1-0",
        "tut_sec": 30,
        "rom_notes": "Deep stretch at bottom without shoulder strain",
        "grip_variations": ["Neutral Grip", "Pronated Grip", "Semi-Pronated"]
    },
    {
        "name": "Lat Pulldown (Wide Grip)",
        "category": "back",
        "primary_muscle": "Lats",
        "secondary_muscles": ["Biceps", "Rear Delts", "Upper Back"],
        "movement_pattern": "pull",
        "equipment": "cable",
        "difficulty": "beginner",
        "skill_level": "beginner",
        "instructions": ["Grasp bar slightly wider than shoulder width", "Drive elbows down and back to upper chest", "Squeeze lats at bottom and control return"],
        "common_mistakes": ["Leaning back excessively", "Pulling behind neck", "Using momentum"],
        "safety_tips": ["Keep chest elevated and shoulders depressed"],
        "alternatives": ["Pull-Ups", "Assisted Pull-Up Machine", "Single Arm Lat Pulldown"],
        "progressions": ["Weighted Pull-Ups"],
        "regressions": ["Band Pulldown"],
        "warmup_suggestions": ["Scapular Pulls 2x10"],
        "estimated_calories_per_min": 6.0,
        "typical_rpe": 7.5,
        "typical_rest_sec": 90,
        "tempo": "2-0-1-1",
        "tut_sec": 32,
        "rom_notes": "Full overhead stretch to chest touch",
        "grip_variations": ["Overhand Wide", "Underhand Neutral", "V-Bar"]
    },
    {
        "name": "Barbell Bent-Over Row",
        "category": "back",
        "primary_muscle": "Mid Back",
        "secondary_muscles": ["Lats", "Rhomboids", "Biceps", "Lower Back"],
        "movement_pattern": "pull",
        "equipment": "barbell",
        "difficulty": "intermediate",
        "skill_level": "intermediate",
        "instructions": ["Hinge hips to 45 degrees with flat spine", "Pull barbell towards upper waist", "Lower with control without rounding back"],
        "common_mistakes": ["Rounding lower spine", "Standing too upright"],
        "safety_tips": ["Engage core abdominal bracing before lifting"],
        "alternatives": ["Chest-Supported T-Bar Row", "Seated Cable Row", "Single Arm DB Row"],
        "progressions": ["Pendlay Row"],
        "regressions": ["Supported Machine Row"],
        "warmup_suggestions": ["Cat-Cow Stretch", "Hip Hinge Warmup"],
        "estimated_calories_per_min": 7.2,
        "typical_rpe": 8.0,
        "typical_rest_sec": 120,
        "tempo": "2-0-1-0",
        "tut_sec": 30,
        "rom_notes": "Bar contacts lower ribs/navel",
        "grip_variations": ["Overhand Grip", "Underhand Grip"]
    },
    {
        "name": "Dumbbell Lateral Raise",
        "category": "shoulders",
        "primary_muscle": "Side Delts",
        "secondary_muscles": ["Traps"],
        "movement_pattern": "isolation",
        "equipment": "dumbbell",
        "difficulty": "beginner",
        "skill_level": "beginner",
        "instructions": ["Stand tall with dumbbells at sides", "Raise arms out to 90 degrees in scapular plane", "Pause briefly at top and lower smoothly"],
        "common_mistakes": ["Shrugging shoulders", "Swinging body for momentum", "Lifting above parallel"],
        "safety_tips": ["Keep thumbs slightly higher than pinkies (scapular alignment)"],
        "alternatives": ["Cable Lateral Raise", "Machine Side Raise"],
        "progressions": ["Lean-Away Cable Lateral Raise"],
        "regressions": ["Light Band Lateral Raise"],
        "warmup_suggestions": ["Shoulder Dislocates"],
        "estimated_calories_per_min": 5.0,
        "typical_rpe": 8.5,
        "typical_rest_sec": 60,
        "tempo": "2-1-1-0",
        "tut_sec": 36,
        "rom_notes": "Raise to shoulder height",
        "grip_variations": ["Neutral Grip", "Slight Internal Rotation"]
    },
    {
        "name": "Barbell Back Squat",
        "category": "quads",
        "primary_muscle": "Quads",
        "secondary_muscles": ["Glute Max", "Hamstrings", "Lower Back", "Core"],
        "movement_pattern": "squat",
        "equipment": "barbell",
        "difficulty": "advanced",
        "skill_level": "advanced",
        "instructions": ["Position bar on upper traps", "Unrack and take solid stance shoulder-width apart", "Break at hips and knees simultaneously", "Squat to parallel or lower and drive upwards"],
        "common_mistakes": ["Knees caving inwards (valgus)", "Heels lifting off ground", "Rounding back at bottom"],
        "safety_tips": ["Use safety pins in power rack", "Maintain intra-abdominal pressure (valsalva)"],
        "alternatives": ["Goblet Squat", "Leg Press", "Smith Machine Squat"],
        "progressions": ["Pause Squat", "Front Squat"],
        "regressions": ["Bodyweight Squat", "Goblet Squat"],
        "warmup_suggestions": ["Ankle Mobility Drills", "Bodyweight Squats 2x10"],
        "estimated_calories_per_min": 9.0,
        "typical_rpe": 8.5,
        "typical_rest_sec": 180,
        "tempo": "3-1-1-0",
        "tut_sec": 40,
        "rom_notes": "Hip crease below top of knee",
        "grip_variations": ["High Bar", "Low Bar"]
    },
    {
        "name": "Romanian Deadlift (RDL)",
        "category": "hamstrings",
        "primary_muscle": "Hamstrings",
        "secondary_muscles": ["Glute Max", "Lower Back", "Forearms"],
        "movement_pattern": "hinge",
        "equipment": "barbell",
        "difficulty": "intermediate",
        "skill_level": "intermediate",
        "instructions": ["Hold bar with shoulder-width grip", "Push hips backward with soft knee bend", "Lower bar along shins until maximum hamstring stretch", "Drive hips forward to stand"],
        "common_mistakes": ["Squatting down instead of hinging", "Rounding lower spine"],
        "safety_tips": ["Keep bar close to body throughout motion"],
        "alternatives": ["Dumbbell RDL", "Single Leg RDL", "Lying Hamstring Curl"],
        "progressions": ["Deficit RDL"],
        "regressions": ["Dumbbell RDL"],
        "warmup_suggestions": ["Hamstring Dynamic Stretch", "Glute Bridges"],
        "estimated_calories_per_min": 8.0,
        "typical_rpe": 8.0,
        "typical_rest_sec": 120,
        "tempo": "3-1-1-0",
        "tut_sec": 35,
        "rom_notes": "Mid-shin level without lumbar flexion",
        "grip_variations": ["Overhand", "Hook Grip"]
    },
    {
        "name": "Cable Bicep Curl (Ez-Bar)",
        "category": "biceps",
        "primary_muscle": "Biceps",
        "secondary_muscles": ["Brachialis", "Forearms"],
        "movement_pattern": "isolation",
        "equipment": "cable",
        "difficulty": "beginner",
        "skill_level": "beginner",
        "instructions": ["Attach Ez-Bar to low cable pulley", "Curl bar upwards keeping elbows pinned to sides", "Squeeze peak contraction at top and lower steadily"],
        "common_mistakes": ["Swinging hips", "Elbows flaring or moving forward"],
        "safety_tips": ["Avoid hyperextending wrist joint"],
        "alternatives": ["Dumbbell Hammer Curl", "Barbell Preacher Curl"],
        "progressions": ["Incline DB Curl"],
        "regressions": ["Band Curl"],
        "warmup_suggestions": ["Wrist Mobility Rotations"],
        "estimated_calories_per_min": 5.0,
        "typical_rpe": 8.5,
        "typical_rest_sec": 60,
        "tempo": "2-0-1-1",
        "tut_sec": 30,
        "rom_notes": "Full arm extension to chin height curl",
        "grip_variations": ["Supinated", "Semi-Supinated"]
    },
    {
        "name": "Tricep Rope Overhead Extension",
        "category": "triceps",
        "primary_muscle": "Triceps Long Head",
        "secondary_muscles": ["Triceps Lateral Head"],
        "movement_pattern": "isolation",
        "equipment": "cable",
        "difficulty": "beginner",
        "skill_level": "beginner",
        "instructions": ["Attach rope to low or high pulley", "Extend hands overhead and flare rope at lockout", "Lower with control into deep stretch"],
        "common_mistakes": ["Arching back excessively", "Flaring elbows outwards"],
        "safety_tips": ["Brace core to keep spine stable overhead"],
        "alternatives": ["Skullcrushers", "Tricep Dips", "Rope Pushdowns"],
        "progressions": ["Incline DB French Press"],
        "regressions": ["Standard Rope Pushdown"],
        "warmup_suggestions": ["Tricep Stretch 2x15s"],
        "estimated_calories_per_min": 5.2,
        "typical_rpe": 8.0,
        "typical_rest_sec": 60,
        "tempo": "2-1-1-0",
        "tut_sec": 32,
        "rom_notes": "Deep elbow flexion to full lockout extension",
        "grip_variations": ["Rope Grip", "EZ-Bar"]
    },
    {
        "name": "Hanging Leg Raise",
        "category": "core",
        "primary_muscle": "Lower Abs",
        "secondary_muscles": ["Upper Abs", "Hip Flexors", "Grip Strength"],
        "movement_pattern": "rotation",
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "skill_level": "intermediate",
        "instructions": ["Hang from pull-up bar with overhand grip", "Curv spine and raise legs/knees towards chest", "Lower slowly without swinging body"],
        "common_mistakes": ["Swinging body like a pendulum", "Using hip flexors only without pelvic tilt"],
        "safety_tips": ["Engage lat muscles to stabilize shoulder joint"],
        "alternatives": ["Captain's Chair Leg Raise", "Reverse Crunches"],
        "progressions": ["Toes-to-Bar"],
        "regressions": ["Bent Knee Hanging Raise", "Lying Reverse Crunch"],
        "warmup_suggestions": ["Plank hold 30s"],
        "estimated_calories_per_min": 5.5,
        "typical_rpe": 8.5,
        "typical_rest_sec": 60,
        "tempo": "2-0-1-1",
        "tut_sec": 28,
        "rom_notes": "Thighs parallel to floor or higher",
        "grip_variations": ["Overhand", "Neutral"]
    }
]

def seed_master_exercises(db: Session):
    existing_count = db.query(MasterExercise).count()
    if existing_count > 0:
        return existing_count
    
    for ex_dict in MASTER_EXERCISES_DATA:
        ex = MasterExercise(**ex_dict)
        db.add(ex)
    db.commit()
    return len(MASTER_EXERCISES_DATA)
